spring:
  application:
    name: history_social_backend

  datasource:
    url: jdbc:postgresql://localhost:5432/history_social
    driver-class-name: org.postgresql.Driver
  
  flyway:
    enabled: false
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    time-zone: Asia/Ho_Chi_Minh


  config:
    import: "classpath:application-secret.yaml"

server:
  port: 8080
  servlet:
    context-path: /history_social


messaging:
  redis:
    stream:
      name: social-events-stream
      consumer-group: notification-consumer-group
      consumer-name: notification-consumer-${random.uuid}
      batch-size: 10
      poll-timeout: 2000
      pending-messages-check-interval: 60000  # 60s
      max-retry-count: 5
      claim-min-idle-time: 300000  # 5 minutes
