spring:
    datasource:
        username: postgres
        password: Vilan26?
    mail:
        host: smtp.gmail.com
        port: 587
        username: sancaulongnhom6@gmail.com
        password: wiorrhajexjqvayt
        properties:
        mail:
            smtp:
            auth: true
            starttls:
                enable: true
jwt:
    secret: 2d0ab38a61cee7cd7c7ce34c7fc5d56c4ad7a2659c6ac959247e16d8105f9a48
    valid-duration: 3600000 # 1 hour in milliseconds
    refresh-duration: 604800000 # 7 days in milliseconds

handlePayment:
    antiDuplicateSeconds: 45


cloudinary:
  cloud-name: dxjkyg5os
  api-key:    825925626416493
  api-secret: S1ELpLQVl6QnF4z_86-5ckmB_BQ